name: Crowdin Context Generation

on:
    workflow_dispatch:
        inputs:
            test_lang:
                description: Select a language to generate UI flows for
                required: true
                type: choice
                default: '["cs"]'
                options:
                    - '["cs"]'
                    - '["fr"]'
                    - '["de"]'
                    - '["es"]'
                    - '["pt"]'

permissions:
    id-token: write # for fetching the OIDC token
    contents: read # for actions/checkout
    pull-requests: write # for dflook comments on PR

env:
    SDL_VIDEODRIVER: dummy
    CROWDIN_COMMENT_PATH: ${{ github.workspace }}/tests/core-crowdin-comment.md
    TREZOR_PYTEST_LOGS_DIR: ${{ github.workspace }}/tests/

jobs:
    core_emu:
        name: Build emu (${{ matrix.model }}, ${{ matrix.coins }}, ${{ matrix.type }}, ${{ matrix.asan }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                model: [T2T1, T3B1, T3T1, T3W1]
                coins: [universal, btconly]
                type: ${{ fromJSON(github.event_name == 'schedule' && '["normal", "debuglink"]' || '["debuglink"]') }}
                asan: [noasan]
                exclude:
                    - type: normal
                      asan: asan
        env:
            TREZOR_MODEL: ${{ matrix.model }}
            BITCOIN_ONLY: ${{ matrix.coins == 'universal' && '0' || '1' }}
            PYOPT: ${{ matrix.type == 'debuglink' && '0' || '1' }}
            ADDRESS_SANITIZER: ${{ matrix.asan == 'asan' && '1' || '0' }}
            LSAN_OPTIONS: "suppressions=../../asan_suppressions.txt"
            QUIET_MODE: 1
            DISABLE_TROPIC: 0
        steps:
            - uses: actions/checkout@v6
              with:
                  submodules: recursive
            - uses: ./.github/actions/environment
            - run: nix-shell --run "uv run make -C core build_bootloader_emu"
              if: matrix.coins == 'universal' && matrix.asan == 'noasan'
            - run: nix-shell --run "uv run make -C core build_unix_frozen"
            - run: nix-shell --arg fullDeps true --run "cd vendor/ts-tvl && poetry env use 3.12 && poetry install && poetry run model_server tcp -c ../../tests/tropic_model/config.yml > ../../tests/trezor-tropic-model.log 2>&1 &"
            - run: nix-shell --run "uv run make -C core test_emu_sanity"
            - run: cp core/build/unix/trezor-emu-core core/build/unix/trezor-emu-core-${{ matrix.model }}-${{ matrix.coins }}
            - uses: actions/upload-artifact@v6
              with:
                  name: core-emu-${{ matrix.model }}-${{ matrix.coins }}-${{ matrix.type }}-${{ matrix.asan }}
                  path: |
                      core/build/unix/trezor-emu-core*
                      core/build/bootloader_emu/bootloader.elf
                  retention-days: 7

    core_emu_arm:
        if: github.event_name == 'schedule'
        name: Build emu arm
        runs-on: ubuntu-latest-arm64
        strategy:
            fail-fast: false
            matrix:
                model: [T2T1, T3B1, T3T1, T3W1]
                coins: [universal]
                type: [debuglink]
                asan: [noasan]
                exclude:
                    - type: normal
                      asan: asan
        env:
            TREZOR_MODEL: ${{ matrix.model }}
            BITCOIN_ONLY: ${{ matrix.coins == 'universal' && '0' || '1' }}
            PYOPT: ${{ matrix.type == 'debuglink' && '0' || '1' }}
            ADDRESS_SANITIZER: ${{ matrix.asan == 'asan' && '1' || '0' }}
            LSAN_OPTIONS: "suppressions=../../asan_suppressions.txt"
            QUIET_MODE: 1
        steps:
            - uses: actions/checkout@v6
              with:
                  submodules: recursive
            - uses: ./.github/actions/environment
            - run: nix-shell --run "uv run make -C core build_bootloader_emu"
              if: matrix.coins == 'universal'
            - run: nix-shell --run "uv run make -C core build_unix_frozen"
            - run: mv core/build/unix/trezor-emu-core core/build/unix/trezor-emu-arm-core-${{ matrix.model }}-${{ matrix.coins }}
            - uses: actions/upload-artifact@v6
              with:
                  name: core-emu-arm-${{ matrix.model }}-${{ matrix.coins }}-${{ matrix.type }}-${{ matrix.asan }}
                  path: |
                      core/build/unix/trezor-emu-*
                      core/build/bootloader_emu/bootloader.elf
                  retention-days: 2

    core_unit_python_test:
        name: Python unit tests (${{ matrix.model }}, ${{ matrix.asan }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                model: [T2T1, T3B1, T3T1, T3W1]
                asan: [noasan]
        env:
            TREZOR_MODEL: ${{ matrix.model }}
            ADDRESS_SANITIZER: ${{ matrix.asan == 'asan' && '1' || '0' }}
            LSAN_OPTIONS: "suppressions=../../asan_suppressions.txt"
            DISABLE_TROPIC: 0
        steps:
            - uses: actions/checkout@v6
              with:
                  submodules: recursive
            - uses: ./.github/actions/environment
            - run: nix-shell --run "uv run make -C core build_unix"
            - run: nix-shell --arg fullDeps true --run "cd vendor/ts-tvl && poetry env use 3.12 && poetry install && poetry run model_server tcp -c ../../tests/tropic_model/config.yml > ../../tests/trezor-tropic-model.log 2>&1 &"
            - run: nix-shell --run "uv run make -C core test"
            - run: nix-shell --run "uv run make -C core test_emu_sanity" # sanity check non-frozen emulator

    # Device tests for Core. Running device tests and also comparing screens
    # with the expected UI result.
    # See artifacts for a comprehensive report of UI.
    # See [docs/tests/ui-tests](../tests/ui-tests.md) for more info.
    core_device_test:
        name: Device tests (${{ matrix.model }}, ${{ matrix.coins }}, ${{ matrix.asan }}, ${{ matrix.lang }})
        runs-on: ubuntu-latest
        needs: core_emu
        strategy:
            fail-fast: false
            matrix:
                model: [T2T1, T3B1, T3T1, T3W1]
                coins: [universal, btconly]
                asan: [noasan]
                lang: ${{ fromJSON(inputs.test_lang) }}
                include:
                    - lang: '["en"]'

        env:
            TREZOR_PROFILING: ${{ matrix.asan == 'noasan' && '1' || '0' }}
            TREZOR_MODEL: ${{ matrix.model }}
            ADDRESS_SANITIZER: ${{ matrix.asan == 'asan' && '1' || '0' }}
            PYTEST_TIMEOUT: ${{ matrix.asan == 'asan' && 600 || 400 }}
            ACTIONS_DO_UI_TEST: ${{ matrix.coins == 'universal' && matrix.asan == 'noasan' }}
            TEST_LANG: ${{ matrix.lang }}
            TESTOPTS: "--durations 10 --session-timeout 1800" # 30m pytest global timeout
        timeout-minutes: 40
        steps:
            - uses: actions/checkout@v6
              with:
                  submodules: recursive
            - uses: actions/download-artifact@v7
              with:
                  name: core-emu-${{ matrix.model }}-${{ matrix.coins }}-debuglink-${{ matrix.asan }}
                  path: core/build
            - run: chmod +x core/build/unix/trezor-emu-core*
            - uses: ./.github/actions/environment
            - name: Start Tropic model
              if: ${{ env.TREZOR_MODEL == 'T3W1' && env.ACTIONS_DO_UI_TEST != 'true' }} # ACTIONS_DO_UI_TEST refers to the test_emu_ui_multicore below which uses --control-emulators and starts tvl internally
              run: nix-shell --arg fullDeps true --run "cd vendor/ts-tvl && poetry env use 3.12 && poetry install && poetry run model_server tcp -c ../../tests/tropic_model/config.yml > ../../tests/trezor-tropic-model.log 2>&1 &"
            - run: nix-shell --run "uv run make -C core ${{ env.ACTIONS_DO_UI_TEST == 'true' && 'test_emu_ui_multicore' || 'test_emu' }}"
            - run: tail -v -n50 tests/trezor*.log || true
              if: failure()
            - uses: actions/upload-artifact@v6
              with:
                  name: core-test-device-${{ matrix.model }}-${{ matrix.coins }}-${{ matrix.lang }}-${{ matrix.asan }}
                  path: tests/trezor*.log
                  retention-days: 7
              if: always()
            - uses: ./.github/actions/ui-report
              with:
                  model: ${{ matrix.model }}
                  lang: ${{ matrix.lang }}
                  status: ${{ job.status }}
              if: ${{ always() && env.ACTIONS_DO_UI_TEST == 'true' }}
              continue-on-error: true
            - uses: ./.github/actions/upload-coverage

    # Click tests - UI.
    # See [docs/tests/click-tests](../tests/click-tests.md) for more info.
    core_click_test:
        name: Click tests (${{ matrix.model }}, ${{ matrix.asan }}, ${{ matrix.lang }})
        runs-on: ubuntu-latest
        needs: core_emu
        timeout-minutes: 40
        strategy:
            fail-fast: false
            matrix:
                model: [T2T1, T3B1, T3T1, T3W1]
                asan: [noasan]
                lang: ${{ fromJSON(inputs.test_lang) }}
        env:
            TREZOR_PROFILING: ${{ matrix.asan == 'noasan' && '1' || '0' }}
            # MULTICORE: 4  # more could interfere with other jobs
            PYTEST_TIMEOUT: 400
            TEST_LANG: ${{ matrix.lang }}
            TESTOPTS: "--durations 10"
        steps:
            - uses: actions/checkout@v6
              with:
                  submodules: recursive
            - uses: actions/download-artifact@v7
              with:
                  name: core-emu-${{ matrix.model }}-universal-debuglink-${{ matrix.asan }}
                  path: core/build
            - run: chmod +x core/build/unix/trezor-emu-core*
            - uses: ./.github/actions/environment
            - run: nix-shell --run "uv run make -C core test_emu_click_ui_multicore"
              if: ${{ matrix.asan == 'noasan' }}
            - run: nix-shell --run "uv run make -C core test_emu_click"
              if: ${{ matrix.asan == 'asan' }}
            - uses: actions/upload-artifact@v6
              with:
                  name: core-test-click-${{ matrix.model }}-${{ matrix.lang }}-${{ matrix.asan }}
                  path: tests/trezor*.log
                  retention-days: 7
              if: always()
            - uses: ./.github/actions/ui-report
              with:
                  model: ${{ matrix.model }}
                  lang: ${{ matrix.lang }}
                  status: ${{ job.status }}
              if: always()
              continue-on-error: true
            - uses: ./.github/actions/upload-coverage

    # Persistence tests - UI.
    core_persistence_test:
        name: Persistence tests (${{ matrix.model }}, ${{ matrix.asan }})
        runs-on: ubuntu-latest
        needs: core_emu
        timeout-minutes: 30
        strategy:
            fail-fast: false
            matrix:
                model: [T2T1, T3B1, T3T1, T3W1]
                asan: [noasan]
        env:
            TREZOR_PROFILING: ${{ matrix.asan == 'noasan' && '1' || '0' }}
            PYTEST_TIMEOUT: 400
        steps:
            - uses: actions/checkout@v6
              with:
                  submodules: recursive
            - uses: actions/download-artifact@v7
              with:
                  name: core-emu-${{ matrix.model }}-universal-debuglink-${{ matrix.asan }}
                  path: core/build
            - run: chmod +x core/build/unix/trezor-emu-core*
            - uses: ./.github/actions/environment
            - name: Start Tropic model
              if: ${{ matrix.model == 'T3W1' }}
              run: nix-shell --arg fullDeps true --run "cd vendor/ts-tvl && poetry env use 3.12 && poetry install && poetry run model_server tcp -c ../../tests/tropic_model/config.yml > ../../tests/trezor-tropic-model.log 2>&1 &"
            - run: nix-shell --run "uv run make -C core test_emu_persistence_ui"
              if: ${{ matrix.asan == 'noasan' }}
            - run: nix-shell --run "uv run make -C core test_emu_persistence"
              if: ${{ matrix.asan == 'asan' }}
            - uses: ./.github/actions/ui-report
              with:
                  model: ${{ matrix.model }}
                  lang: en
                  status: ${{ job.status }}
              if: always()
              continue-on-error: true
            - uses: ./.github/actions/upload-coverage
            - uses: actions/upload-artifact@v6
              with:
                  name: core-test-persistence-${{ matrix.model }}-${{ matrix.asan }}
                  path: |
                      tests/trezor*.log
                  retention-days: 7
              if: always()

    core_ui_comment:
        name: Post comment with UI flows
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - run: sleep 1m # try avoiding github api rate limit
            - run: |
                  python ci/make_crowdin_comment.py "${{ github.run_id }}" '${{ inputs.test_lang }}' > ${{ env.CROWDIN_COMMENT_PATH }}
                  cat ${{ env.CROWDIN_COMMENT_PATH }} >> $GITHUB_STEP_SUMMARY
            - uses: ./.github/actions/ui-comment
              if: github.event_name == 'pull_request'
            - name: Configure aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::538326561891:role/gh_actions_deploy_dev_firmware_data
                  aws-region: eu-west-1

            - run: python ci/make_summary_htmls.py "index" '${{ inputs.test_lang }}' "tests/ui_tests/reporting/"
            - run: python ci/make_summary_htmls.py "diff" '${{ inputs.test_lang }}' "tests/ui_tests/reporting/"
            - name: Upload per-language HTML summaries to S3
              run: |
                  cd tests/ui_tests/reporting/
                  for F in *.html
                  do
                    aws s3 cp $F s3://data.trezor.io/dev/firmware/ui_report/${{ github.run_id }}/$F
                  done
